language: python
python:
- '3.6'
services: docker
sudo: required
env:
  global:
  - ESPA_ENV=dev
  - ESPA_MEMCACHE_HOST=localhost:30070
  - ESPA_CONFIG_PATH=${TRAVIS_BUILD_DIR}/run/config.ini
  - ESPA_API_EMAIL_RECEIVE=someone@nowhere.com
cache: pip
install:
- pip install -e .
- pip install -e .[test]
- pip install codecov
script:
- "travis_wait 30 sleep 1800 &"
- "pytest --cov=./"
after_success:
- codecov
# deploy:
#   - provider: script
#     script: make docker-deploy
#     on:
#       branch:
#         - master
#         - develop
#         - laboratory
notifications:
  email:
    on_success: never
    on_failure: change
