language: python
python:
- '3.6'
services: docker
sudo: required
env:
  global:
  - ESPA_API_ENV=dev
  - ESPA_API_MEMCACHE_HOST=localhost:30070
  - ESPA_API_CONFIG_PATH=${TRAVIS_BUILD_DIR}/run/config.ini
  - ESPA_API_EMAIL_RECEIVE=someone@nowhere.com
  - ESPA_API_LOG_STDOUT=True
  - ESPA_API_DB_HOST=localhost
  - ESPA_API_DB_PORT=30080
cache: pip
before_install:
- make docker-deps-up
install:
- pip install -e .
- pip install -e .[test]
- pip install codecov
script:
- "travis_wait 30 sleep 1800 &"
- "pytest --cov=./"
after_success:
- make docker-deps-down
- codecov
deploy:
  - provider: script
    script: make docker-deploy
    on:
      branch:
        - master
        - develop
notifications:
  email:
    on_success: never
    on_failure: change
