language: python
python:
- '2.7'
services: docker
sudo: required
env:
  global:
  - ESPA_ENV=dev
  - ESPA_MEMCACHE_HOST=localhost:30070
  - ESPA_CONFIG_PATH=${TRAVIS_BUILD_DIR}/run/config.ini
  - ESPA_API_EMAIL_RECEIVE=someone@nowhere.com
cache: pip
install:
- pip install -r setup/requirements.txt
- pip install codecov
script:
- "travis_wait 30 sleep 1800 &"
- "run/runtests"
after_success:
- codecov
deploy:
  - provider: script
    script: make deploy
    on:
      branch: master
  - provider: script
    script: make deploy
    on:
      branch: develop
  - provider: script
    script: make deploy
    on:
      branch: laboratory
